{% set name = "jupyter_innotater" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f1424cf06b90d79c10dd9fd1768734a33b9e4b7f8b0df3b2daee26ea983a1ef

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.4.0
    - pypng >=0.0.19
    - jupyterlab >=3.0
    - jupyter-packaging >= 0.11.0
    - ipywidgets >=7.6.5

test:
  imports:
    - jupyter_innotater
    - jupyter_packaging

about:
  home: https://github.com/ideonate/jupyter-innotater
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Annotate data including image bounding boxes inline within your Jupyter notebook in python

extra:
  recipe-maintainers:
    - costrouc
    - rigzba21
